### ISSUE TITLE
not backwards compatible with 2.7

### ISSUE THREAD

**Issue by promediacorp** [Sigm0oid/dynamodb-geo.py#38]
i know, i know, i should have migrated to 3.x ;)

but in the meantime, im having trouble getting it to work on 2.7, here is the error:

```
File "/Users/myusername/git/myproject/venv/lib/python2.7/site-packages/dynamodbgeo/s2/S2Manager.py", line 6
    def generateGeohash(self, geoPoint: 'GeoPoint'):

SyntaxError: invalid syntax
```
any suggestions to get it to work with 2.7?

**Comment by Sigm0oid** [comment]
Hi Promediacorp,
The error you're seeing is due to python3 type hint style used [here](https://github.com/Sigm0oid/dynamodb-geo.py/blob/d2f832577c82d8322b688bfa85badbd6252337e5/dynamodbgeo/s2/S2Manager.py#L6) that is considered as [ syntax violation](https://stackoverflow.com/a/41936489/5873551) for python2.7.

As Python 2 End of Life Announced as January 1st 2020(Even AWS does not support creating new lambda's in 2.7 anymore). We decided initially to support mainly python3.x +. 
Sorry for the inconvenience!
